# Copyright OxidOS Automotive 2024.

[package]
name = "tock-configurator"
version.workspace = true
edition.workspace = true
rust-version = "1.61"

[dependencies]
cursive = "0.20.0"
parse = { path = "../parse" }
cursive-aligned-view = "0.6.0"
serde_json = "1.0.116"
serde = { version = "1.0.197", default-features = false, features = [
    "derive",
    "alloc",
] }
# Supported chips
nrf52833 = { path = "../chips/nrf52833" }
