# Copyright OxidOS Automotive 2024.

[package]
name = "nrf52833"
version.workspace = true
edition.workspace = true

[dependencies]
parse = { path = "../../parse" }
serde = { version = "1.0.197", default-features = false, features = [
    "derive",
    "alloc",
] }
serde_json = "1.0.116"
quote = "1.0.36"

common = { path = "../common" }
proc-macro2 = "1.0.86"

